# Site settings
title: XGuider Blog
SEOTitle: XGuider的博客 | XGuider Blog
header-img: img/home-bg-art.jpg
email: 1275660493@qq.com
description: "@XGuider,不要让任何事情成为你不去学习的理由！"
keyword: "XGuider, @XGuider, XGuider的博客,XGuider Blog, 博客, 个人网站, 互联网"
url: "https://XGuider.github.io"              # your host, for absolute URL
baseurl: ""                                  # empty string for GitHub Pages root repository (username.github.io)



# SNS settings
RSS: false
github_username:    XGuider

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins
# GitHub Pages支持的插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# LiveRe setttings
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8yODkzOC81NTA3


# Analytics settings
# Baidu Analytics (百度统计)
ba_track_id: 969b089e87ca4b02f96f2c1ee3553b06

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx (请更新为你的Google Analytics ID)
ga_domain: XGuider.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "不要让任何事情成为你不去学习的理由！"
sidebar-avatar: /img/favicon.ico      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video

# Friends
friends: [{
        title: "XGuider GitHub",
        href: "https://XGuider.github.io"
    }
]
