# Site settings
title: "XGuider Blog"
seo_title: "XGuider的博客 | XGuider Blog"
header_img: "img/home-bg-art.webp"
email: "1275660493@qq.com"
description: "@XGuider,不要让任何事情成为你不去学习的理由！"
keywords: ["XGuider", "@XGuider", "XGuider的博客", "XGuider Blog", "博客", "个人网站", "互联网", "Web开发", "技术博客"]
url: "https://xguider.github.io"
baseurl: ""

# Modern SEO and social media
lang: "zh-CN"
author: "XGuider"
twitter:
  username: "XGuider"
  card: "summary_large_image"
facebook:
  app_id: ""
  publisher: ""
linkedin_username: "xguider"
instagram_username: "xguider"



# SNS settings
RSS: false
github_username:    XGuider

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md","scripts","_posts/*.docx","_posts/*.doc","_posts/*.pdf"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Modern Jekyll plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-pwa-plugin



# Modern Markdown configuration
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: _your_disqus_short_name_

# LiveRe setttings
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8yODkzOC81NTA3


# Modern analytics
analytics:
  google:
    tag_id: "G-XXXXXXXXXX"  # GA4 Measurement ID
  baidu:
    tracking_id: "969b089e87ca4b02f96f2c1ee3553b06"
  plausible:
    domain: "xguider.github.io"
  umami:
    website_id: ""
    src: ""

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "不要让任何事情成为你不去学习的理由！"
sidebar-avatar: /img/favicon.ico      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video

# Friends
friends: [{
        title: "XGuider GitHub",
        href: "https://XGuider.github.io"
    }
]
